cc_binary(
    name = "serenity",
    srcs = ["main.cc"],
    deps = [":game_map"],
)

cc_library(
    name = "game_map",
    srcs = ["game_map.cc"],
    hdrs = ["game_map.h"],
    visibility = ["//visibility:public"],
)